### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Regomy** [tiredvekster/LightAntiCheat#4]
1. false-positives like VelocityA (maybe because i don't have a vanilla setting of kb) but no one ac detect me for this.
test plugin on 1.8 and more versions before updating !!!!

2. Dear developer, please release updates more often, and about velocitaA, isn't it easier to take checks from other ac? Than to make your own, which also falsely triggers.

[11:41:32 ERROR]: Could not pass event cd to LightAntiCheat v1.1.9

org.bukkit.event.EventException: null

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PandaSpigot-119]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.8.8.jar:git-PandaSpigot-119]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PandaSpigot-119]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:564) ~[patched_1.8.8.jar:git-PandaSpigot-119]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:546) ~[patched_1.8.8.jar:git-PandaSpigot-119]

at me.vekster.lightanticheat.bv.a(Unknown Source) ~[?:?]

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched_1.8.8.jar:git-PandaSpigot-119]

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [patched_1.8.8.jar:git-PandaSpigot-119]

at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23) [patched_1.8.8.jar:git-PandaSpigot-119]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]

at java.lang.Thread.run(Thread.java:840) [?:?]

Caused by: java.lang.IllegalStateException: Asynchronous entity world add!

at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[patched_1.8.8.jar:git-PandaSpigot-119]

at net.minecraft.server.v1_8_R3.World.b(World.java:2880) ~[patched_1.8.8.jar:git-PandaSpigot-119]

at net.minecraft.server.v1_8_R3.Chunk.addEntities(Chunk.java:921) ~[patched_1.8.8.jar:git-PandaSpigot-119]

at net.minecraft.server.v1_8_R3.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:180) ~[patched_1.8.8.jar:git-PandaSpigot-119]

at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:139) ~[patched_1.8.8.jar:git-PandaSpigot-119]

at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118) ~[patched_1.8.8.jar:git-PandaSpigot-119]

at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:145) ~[patched_1.8.8.jar:git-PandaSpigot-119]

at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:91) ~[patched_1.8.8.jar:git-PandaSpigot-119]

at me.vekster.lightanticheat.dc.a(Unknown Source) ~[?:?]

at me.vekster.lightanticheat.dc.b(Unknown Source) ~[?:?]

at me.vekster.lightanticheat.aq.a(Unknown Source) ~[?:?]

at jdk.internal.reflect.GeneratedMethodAccessor112.invoke(Unknown Source) ~[?:?]

at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PandaSpigot-119]

**Comment by tiredvekster** [comment]
Hi! Looks like this exact error has already been reported twice on SpigotMC, but thanks for reporting it as an Issue on GitHub, though. I couldn't reproduce the error so I can't guarantee that I will be able to fix this on the first try. As for using code from other anticheats, this might be a good idea, but it wouldn't solve compatibility issues

**Comment by tiredvekster** [comment]
Hi! Looks like this exact error has already been reported twice on SpigotMC, but thanks for reporting it as an Issue on GitHub, though. I couldn't reproduce the error so I can't guarantee that I will be able to fix this on the first try. As for using code from other anticheats, this might be a good idea, but it wouldn't solve compatibility issues

**Comment by tiredvekster** [comment]
Can you please provide more information about when the error occurs?

**Comment by tiredvekster** [comment]
I've fixed the error in Light 1.2.0, but there may still be some potential compatibility issues remaining.
